apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
  - name: jenkins-harbor-cred
  containers:
  - name: busybox
    image: busybox:latest
    command: ['cat']
    tty: true
  - name: git
    image: alpine/git:latest
    command: ['cat']
    tty: true
  - name: helm
    image: core.c7d.net/c7d/utility-helm:v3.3.5
    command: ['cat']
    tty: true
  - name: jq
    image: core.c7d.net/c7d/jq:latest
    command: ['cat']
    tty: true
  - name: docker
    image: docker:latest
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
